import tiposDeSimbolos from '../tipos-de-simbolos/delegua';

export const palavrasReservadas = {
    cada: tiposDeSimbolos.CADA,
    caso: tiposDeSimbolos.CASO,
    classe: tiposDeSimbolos.CLASSE,
    construtor: tiposDeSimbolos.CONSTRUTOR,
    continua: tiposDeSimbolos.CONTINUA,
    constante: tiposDeSimbolos.CONSTANTE,
    const: tiposDeSimbolos.CONSTANTE,
    de: tiposDeSimbolos.DE,
    e: tiposDeSimbolos.E,
    em: tiposDeSimbolos.EM,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escolha: tiposDeSimbolos.ESCOLHA,
    escreva: tiposDeSimbolos.ESCREVA,
    falhar: tiposDeSimbolos.FALHAR,
    falso: tiposDeSimbolos.FALSO,
    fazer: tiposDeSimbolos.FAZER,
    finalmente: tiposDeSimbolos.FINALMENTE,
    fixo: tiposDeSimbolos.CONSTANTE,
    funcao: tiposDeSimbolos.FUNCAO,
    função: tiposDeSimbolos.FUNÇÃO,
    herda: tiposDeSimbolos.HERDA,
    importar: tiposDeSimbolos.IMPORTAR,
    isto: tiposDeSimbolos.ISTO,
    leia: tiposDeSimbolos.LEIA,
    nulo: tiposDeSimbolos.NULO,
    ou: tiposDeSimbolos.OU,
    padrao: tiposDeSimbolos.PADRAO,
    para: tiposDeSimbolos.PARA,
    pausa: tiposDeSimbolos.PAUSA,
    pegue: tiposDeSimbolos.PEGUE,
    retorna: tiposDeSimbolos.RETORNA,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    senão: tiposDeSimbolos.SENÃO,
    super: tiposDeSimbolos.SUPER,
    sustar: tiposDeSimbolos.SUSTAR,
    tente: tiposDeSimbolos.TENTE,
    tipo: tiposDeSimbolos.TIPO,
    var: tiposDeSimbolos.VARIAVEL,
    variavel: tiposDeSimbolos.VARIAVEL,
    variável: tiposDeSimbolos.VARIAVEL,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};

export const palavrasReservadasMicroGramatica = {
    e: tiposDeSimbolos.E,
    em: tiposDeSimbolos.EM,
    falso: tiposDeSimbolos.FALSO,
    nulo: tiposDeSimbolos.NULO,
    ou: tiposDeSimbolos.OU,
    verdadeiro: tiposDeSimbolos.VERDADEIRO
}