import tiposDeSimbolos from '../../../tipos-de-simbolos/birl';

export default {
    // HORA_DO_SHOW: tiposDeSimbolos.HORA_DO_SHOW,
    // BIRL: tiposDeSimbolos.BIRL,
    // QUE_QUE_CE_QUER_MONSTRAO: tiposDeSimbolos.QUE_QUE_CE_QUER_MONSTRAO,
    // ELE_QUE_A_GENTE_QUER: tiposDeSimbolos.ELE_QUE_A_GENTE_QUER,
    // NAO_VAI_DAR_NAO: tiposDeSimbolos.NAO_VAI_DAR_NAO,
    // QUE_NAO_VAI_DAR_O_QUE: tiposDeSimbolos.QUE_NAO_VAI_DAR_O_QUE,
    // NEGATIVA_BAMBAM: tiposDeSimbolos.NEGATIVA_BAMBAM,
    // MAIS_QUERO_MAIS: tiposDeSimbolos.MAIS_QUERO_MAIS,
    // VAMO_MONSTRO: tiposDeSimbolos.VAMO_MONSTRO,
    // SAI_FILHO_DA_PUTA: tiposDeSimbolos.SAI_FILHO_DA_PUTA,
    // OH_O_HOME_AI_PO: tiposDeSimbolos.OH_O_HOME_AI_PO,
    // AJUDA_O_MALUCO_TA_DOENTE: tiposDeSimbolos.AJUDA_O_MALUCO_TA_DOENTE,
    a: tiposDeSimbolos.A,
    ai: tiposDeSimbolos.AI,
    ajuda: tiposDeSimbolos.AJUDA,
    bambam: tiposDeSimbolos.BAMBAM,
    birl: tiposDeSimbolos.BIRL,
    bora: tiposDeSimbolos.BORA,
    ce: tiposDeSimbolos.CE,
    cumpade: tiposDeSimbolos.CUMPADE,
    da: tiposDeSimbolos.DA,
    dar: tiposDeSimbolos.DAR,
    do: tiposDeSimbolos.DO,
    doente: tiposDeSimbolos.DOENTE,
    ele: tiposDeSimbolos.ELE,
    essa: tiposDeSimbolos.ESSA,
    filho: tiposDeSimbolos.FILHO,
    frango: tiposDeSimbolos.FRANGO,
    gente: tiposDeSimbolos.GENTE,
    home: tiposDeSimbolos.HOME,
    hora: tiposDeSimbolos.HORA,
    mais: tiposDeSimbolos.MAIS,
    maluco: tiposDeSimbolos.MALUCO,
    monstrao: tiposDeSimbolos.MONSTRAO,
    monstro: tiposDeSimbolos.MONSTRO,
    monstrinho: tiposDeSimbolos.MONSTRINHO, // Essa palavra reservada faz referencia a um short int que em C tem 2bytes ou 16 bits, mas não tratamos ela assim, aqui ela é ignorada e a tratamos como um inteiros de 4 bytes ou 32 bits.
    nao: tiposDeSimbolos.NAO,
    negativa: tiposDeSimbolos.NEGATIVA,
    o: tiposDeSimbolos.O,
    oh: tiposDeSimbolos.OH,
    po: tiposDeSimbolos.PO,
    porra: tiposDeSimbolos.PORRA,
    puta: tiposDeSimbolos.PUTA,
    que: tiposDeSimbolos.QUE,
    quer: tiposDeSimbolos.QUER,
    quero: tiposDeSimbolos.QUERO,
    sai: tiposDeSimbolos.SAI,
    show: tiposDeSimbolos.SHOW,
    ta: tiposDeSimbolos.TA,
    vai: tiposDeSimbolos.VAI,
    vamo: tiposDeSimbolos.VAMO,
    ver: tiposDeSimbolos.VER,
    trapezio: tiposDeSimbolos.TRAPEZIO,
};
