import tiposDeSimbolos from '../../../tipos-de-simbolos/calango';

export default {
    algoritmo: tiposDeSimbolos.ALGORITMO,
    ate: tiposDeSimbolos.ATE,
    caracter: tiposDeSimbolos.CARACTER,
    caso: tiposDeSimbolos.CASO,
    de: tiposDeSimbolos.DE,
    escolha: tiposDeSimbolos.ESCOLHA,
    enquanto: tiposDeSimbolos.ENQUANTO,
    entao: tiposDeSimbolos.ENTAO,
    escreva: tiposDeSimbolos.ESCREVA,
    escreval: tiposDeSimbolos.ESCREVAL,
    faca: tiposDeSimbolos.FACA,
    falso: tiposDeSimbolos.FALSO,
    fimEnquanto: tiposDeSimbolos.FIM_ENQUANTO,
    fimEscolha: tiposDeSimbolos.FIM_ESCOLHA,
    fimFuncao: tiposDeSimbolos.FIM_FUNCAO,
    fimPara: tiposDeSimbolos.FIM_PARA,
    fimProcedimento: tiposDeSimbolos.FIM_PROCEDIMENTO,
    fimPrincipal: tiposDeSimbolos.FIM_PRINCIPAL,
    fimSe: tiposDeSimbolos.FIM_SE,
    outroCaso: tiposDeSimbolos.OUTRO_CASO,
    procedimento: tiposDeSimbolos.PROCEDIMENTO,
    inteiro: tiposDeSimbolos.INTEIRO,
    funcao: tiposDeSimbolos.FUNCAO,
    interrompa: tiposDeSimbolos.INTERROMPA,
    leia: tiposDeSimbolos.LEIA,
    logico: tiposDeSimbolos.LOGICO,
    para: tiposDeSimbolos.PARA,
    passo: tiposDeSimbolos.PASSO,
    principal: tiposDeSimbolos.PRINCIPAL,
    real: tiposDeSimbolos.REAL,
    retorna: tiposDeSimbolos.RETORNA,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    texto: tiposDeSimbolos.TIPO_TEXTO,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};
