import tiposDeSimbolos from '../../../tipos-de-simbolos/egua-classico';

export const palavrasReservadas = {
    e: tiposDeSimbolos.E,
    em: tiposDeSimbolos.EM,
    caso: tiposDeSimbolos.CASO,
    classe: tiposDeSimbolos.CLASSE,
    continua: tiposDeSimbolos.CONTINUA,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escolha: tiposDeSimbolos.ESCOLHA,
    escreva: tiposDeSimbolos.ESCREVA,
    falso: tiposDeSimbolos.FALSO,
    fazer: tiposDeSimbolos.FAZER,
    finalmente: tiposDeSimbolos.FINALMENTE,
    função: tiposDeSimbolos.FUNCAO,
    herda: tiposDeSimbolos.HERDA,
    importar: tiposDeSimbolos.IMPORTAR,
    isto: tiposDeSimbolos.ISTO,
    leia: tiposDeSimbolos.LEIA,
    nulo: tiposDeSimbolos.NULO,
    ou: tiposDeSimbolos.OU,
    para: tiposDeSimbolos.PARA,
    padrão: tiposDeSimbolos.PADRAO,
    pausa: tiposDeSimbolos.PAUSA,
    pegue: tiposDeSimbolos.PEGUE,
    retorna: tiposDeSimbolos.RETORNA,
    se: tiposDeSimbolos.SE,
    senãose: tiposDeSimbolos.SENÃOSE,
    senão: tiposDeSimbolos.SENÃO,
    super: tiposDeSimbolos.SUPER,
    tente: tiposDeSimbolos.TENTE,
    var: tiposDeSimbolos.VARIAVEL,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};
