import tiposDeSimbolos from '../../../tipos-de-simbolos/mapler';

export const palavrasReservadas = {
    ate: tiposDeSimbolos.ATE,
    cadeia: tiposDeSimbolos.CADEIA,
    caractere: tiposDeSimbolos.CARACTERE,
    de: tiposDeSimbolos.DE,
    e: tiposDeSimbolos.E,
    enquanto: tiposDeSimbolos.ENQUANTO,
    entao: tiposDeSimbolos.ENTAO,
    escrever: tiposDeSimbolos.ESCREVER,
    faca: tiposDeSimbolos.FACA,
    falso: tiposDeSimbolos.FALSO,
    fim: tiposDeSimbolos.FIM,
    fimenquanto: tiposDeSimbolos.FIM_ENQUANTO,
    fimpara: tiposDeSimbolos.FIM_PARA,
    fimse: tiposDeSimbolos.FIM_SE,
    inicio: tiposDeSimbolos.INICIO,
    inteiro: tiposDeSimbolos.INTEIRO,
    ler: tiposDeSimbolos.LER,
    logico: tiposDeSimbolos.LOGICO,
    nao: tiposDeSimbolos.NEGACAO,
    ou: tiposDeSimbolos.OU,
    para: tiposDeSimbolos.PARA,
    real: tiposDeSimbolos.REAL,
    repita: tiposDeSimbolos.REPITA,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    variaveis: tiposDeSimbolos.VARIAVEIS,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
    vetor: tiposDeSimbolos.VETOR,
};
