import tiposDeSimbolos from '../../../tipos-de-simbolos/pitugues';

export const palavrasReservadasPitugues = {
    cada: tiposDeSimbolos.CADA,
    caso: tiposDeSimbolos.CASO,
    classe: tiposDeSimbolos.CLASSE,
    como: tiposDeSimbolos.COMO,
    construtor: tiposDeSimbolos.CONSTRUTOR,
    continua: tiposDeSimbolos.CONTINUA,
    de: tiposDeSimbolos.DE,
    e: tiposDeSimbolos.E,
    em: tiposDeSimbolos.EM,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escolha: tiposDeSimbolos.ESCOLHA,
    escreva: tiposDeSimbolos.ESCREVA,
    falhar: tiposDeSimbolos.FALHAR,
    falso: tiposDeSimbolos.FALSO,
    fazer: tiposDeSimbolos.FAZER,
    finalmente: tiposDeSimbolos.FINALMENTE,
    funcao: tiposDeSimbolos.FUNCAO,
    função: tiposDeSimbolos.FUNÇÃO,
    importar: tiposDeSimbolos.IMPORTAR,
    imprima: tiposDeSimbolos.IMPRIMA,
    isto: tiposDeSimbolos.ISTO,
    entrada: tiposDeSimbolos.LEIA,
    leia: tiposDeSimbolos.LEIA,
    nada: tiposDeSimbolos.NADA,
    nao: tiposDeSimbolos.NAO,
    não: tiposDeSimbolos.NAO,
    nulo: tiposDeSimbolos.NULO,
    ou: tiposDeSimbolos.OU,
    padrao: tiposDeSimbolos.PADRAO,
    padrão: tiposDeSimbolos.PADRAO,
    para: tiposDeSimbolos.PARA,
    pegue: tiposDeSimbolos.PEGUE,
    quebrar: tiposDeSimbolos.QUEBRAR,
    retorna: tiposDeSimbolos.RETORNA,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    senão: tiposDeSimbolos.SENAO,
    super: tiposDeSimbolos.SUPER,
    sustar: tiposDeSimbolos.SUSTAR,
    tendo: tiposDeSimbolos.TENDO,
    tente: tiposDeSimbolos.TENTE,
    tipo: tiposDeSimbolos.TIPO,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};

export const palavrasReservadasMicroGramatica = {
    e: tiposDeSimbolos.E,
    em: tiposDeSimbolos.EM,
    falso: tiposDeSimbolos.FALSO,
    nulo: tiposDeSimbolos.NULO,
    ou: tiposDeSimbolos.OU,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};
