import tiposDeSimbolos from '../../../tipos-de-simbolos/portugol-studio';

export const palavrasReservadas = {
    cadeia: tiposDeSimbolos.CADEIA,
    caracter: tiposDeSimbolos.CARACTER,
    const: tiposDeSimbolos.CONSTANTE,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escreva: tiposDeSimbolos.ESCREVA,
    e: tiposDeSimbolos.E,
    faca: tiposDeSimbolos.FACA,
    falso: tiposDeSimbolos.FALSO,
    funcao: tiposDeSimbolos.FUNCAO,
    inteiro: tiposDeSimbolos.INTEIRO,
    leia: tiposDeSimbolos.LEIA,
    logico: tiposDeSimbolos.LOGICO,
    nao: tiposDeSimbolos.NEGACAO,
    ou: tiposDeSimbolos.OU,
    para: tiposDeSimbolos.PARA,
    programa: tiposDeSimbolos.PROGRAMA,
    real: tiposDeSimbolos.REAL,
    retorne: tiposDeSimbolos.RETORNE,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    vazio: tiposDeSimbolos.VAZIO,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};
