import tiposDeSimbolos from '../../../tipos-de-simbolos/potigol';

export const palavrasReservadas = {
    Caractere: tiposDeSimbolos.CARACTERE,
    div: tiposDeSimbolos.DIVISAO_INTEIRA,
    e: tiposDeSimbolos.E,
    entao: tiposDeSimbolos.ENTAO,
    então: tiposDeSimbolos.ENTAO,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escreva: tiposDeSimbolos.ESCREVA,
    faca: tiposDeSimbolos.FACA,
    faça: tiposDeSimbolos.FACA,
    falso: tiposDeSimbolos.FALSO,
    fim: tiposDeSimbolos.FIM,
    imprima: tiposDeSimbolos.IMPRIMA,
    Inteiro: tiposDeSimbolos.INTEIRO,
    Logico: tiposDeSimbolos.LOGICO,
    Lógico: tiposDeSimbolos.LOGICO,
    mod: tiposDeSimbolos.MODULO,
    ou: tiposDeSimbolos.OU,
    nao: tiposDeSimbolos.NEGACAO,
    não: tiposDeSimbolos.NEGACAO,
    Real: tiposDeSimbolos.REAL,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    senão: tiposDeSimbolos.SENAO,
    Texto: tiposDeSimbolos.TEXTO,
    var: tiposDeSimbolos.VARIAVEL,
    verdadeiro: tiposDeSimbolos.VERDADEIRO
}