import tiposDeSimbolos from '../../../tipos-de-simbolos/potigol';

export const palavrasReservadas = {
    ate: tiposDeSimbolos.ATE,
    até: tiposDeSimbolos.ATE,
    Caractere: tiposDeSimbolos.CARACTERE,
    caso: tiposDeSimbolos.CASO,
    de: tiposDeSimbolos.DE,
    div: tiposDeSimbolos.DIVISAO_INTEIRA,
    e: tiposDeSimbolos.E,
    escolha: tiposDeSimbolos.ESCOLHA,
    entao: tiposDeSimbolos.ENTAO,
    então: tiposDeSimbolos.ENTAO,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escreva: tiposDeSimbolos.ESCREVA,
    faca: tiposDeSimbolos.FACA,
    faça: tiposDeSimbolos.FACA,
    falso: tiposDeSimbolos.FALSO,
    fim: tiposDeSimbolos.FIM,
    imprima: tiposDeSimbolos.IMPRIMA,
    Inteiro: tiposDeSimbolos.INTEIRO,
    Logico: tiposDeSimbolos.LOGICO,
    Lógico: tiposDeSimbolos.LOGICO,
    mod: tiposDeSimbolos.MODULO,
    ou: tiposDeSimbolos.OU,
    nao: tiposDeSimbolos.NEGACAO,
    não: tiposDeSimbolos.NEGACAO,
    para: tiposDeSimbolos.PARA,
    passo: tiposDeSimbolos.PASSO,
    Real: tiposDeSimbolos.REAL,
    retorne: tiposDeSimbolos.RETORNE,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    senão: tiposDeSimbolos.SENAO,
    Texto: tiposDeSimbolos.TEXTO,
    var: tiposDeSimbolos.VARIAVEL,
    verdadeiro: tiposDeSimbolos.VERDADEIRO
}