import tiposDeSimbolos from '../../../tipos-de-simbolos/prisma';

export const palavrasReservadas = {
    caso: tiposDeSimbolos.CASO,
    classe: tiposDeSimbolos.CLASSE,
    construtor: tiposDeSimbolos.CONSTRUTOR,
    continua: tiposDeSimbolos.CONTINUA,
    e: tiposDeSimbolos.E,
    em: tiposDeSimbolos.EM,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escolha: tiposDeSimbolos.ESCOLHA,
    imprima: tiposDeSimbolos.IMPRIMA,
    falso: tiposDeSimbolos.FALSO,
    fazer: tiposDeSimbolos.FAZER,
    finalmente: tiposDeSimbolos.FINALMENTE,
    funcao: tiposDeSimbolos.FUNCAO,
    função: tiposDeSimbolos.FUNÇÃO,
    importar: tiposDeSimbolos.IMPORTAR,
    isto: tiposDeSimbolos.ISTO,
    leia: tiposDeSimbolos.LEIA,
    local: tiposDeSimbolos.LOCAL,
    nulo: tiposDeSimbolos.NULO,
    ou: tiposDeSimbolos.OU,
    padrao: tiposDeSimbolos.PADRAO,
    padrão: tiposDeSimbolos.PADRAO,
    para: tiposDeSimbolos.PARA,
    cada: tiposDeSimbolos.CADA,
    pegue: tiposDeSimbolos.PEGUE,
    retorna: tiposDeSimbolos.RETORNA,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    senão: tiposDeSimbolos.SENÃO,
    super: tiposDeSimbolos.SUPER,
    sustar: tiposDeSimbolos.SUSTAR,
    tente: tiposDeSimbolos.TENTE,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};
