import tiposDeSimbolos from '../../../tipos-de-simbolos/tenda';

export const palavrasReservadas = {
    até: tiposDeSimbolos.ATÉ,
    cada: tiposDeSimbolos.CADA,
    caso: tiposDeSimbolos.CASO,
    classe: tiposDeSimbolos.CLASSE,
    como: tiposDeSimbolos.COMO,
    construtor: tiposDeSimbolos.CONSTRUTOR,
    continua: tiposDeSimbolos.CONTINUA,
    e: tiposDeSimbolos.E,
    é: tiposDeSimbolos.É,
    em: tiposDeSimbolos.EM,
    então: tiposDeSimbolos.ENTÃO,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escolha: tiposDeSimbolos.ESCOLHA,
    exiba: tiposDeSimbolos.EXIBA,
    falhar: tiposDeSimbolos.FALHAR,
    falso: tiposDeSimbolos.FALSO,
    faça: tiposDeSimbolos.FAÇA,
    fazer: tiposDeSimbolos.FAZER,
    fim: tiposDeSimbolos.FIM,
    finalmente: tiposDeSimbolos.FINALMENTE,
    fixo: tiposDeSimbolos.CONSTANTE,
    função: tiposDeSimbolos.FUNÇÃO,
    herda: tiposDeSimbolos.HERDA,
    importar: tiposDeSimbolos.IMPORTAR,
    isto: tiposDeSimbolos.ISTO,
    leia: tiposDeSimbolos.LEIA,
    não: tiposDeSimbolos.NÃO,
    nulo: tiposDeSimbolos.NADA,
    ou: tiposDeSimbolos.OU,
    padrao: tiposDeSimbolos.PADRAO,
    para: tiposDeSimbolos.PARA,
    pegue: tiposDeSimbolos.PEGUE,
    retorna: tiposDeSimbolos.RETORNA,
    se: tiposDeSimbolos.SE,
    seja: tiposDeSimbolos.SEJA,
    senão: tiposDeSimbolos.SENÃO,
    super: tiposDeSimbolos.SUPER,
    sustar: tiposDeSimbolos.SUSTAR,
    tem: tiposDeSimbolos.TEM,
    tendo: tiposDeSimbolos.TENDO,
    tente: tiposDeSimbolos.TENTE,
    tipo: tiposDeSimbolos.TIPO,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};
