import tiposDeSimbolos from '../../../tipos-de-simbolos/visualg';

export default {
    algoritmo: tiposDeSimbolos.ALGORITMO,
    ate: tiposDeSimbolos.ATE,
    caractere: tiposDeSimbolos.CARACTERE,
    caso: tiposDeSimbolos.CASO,
    de: tiposDeSimbolos.DE,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escolha: tiposDeSimbolos.ESCOLHA,
    escreva: tiposDeSimbolos.ESCREVA,
    escreval: tiposDeSimbolos.ESCREVA_LINHA,
    faca: tiposDeSimbolos.FACA,
    falso: tiposDeSimbolos.FALSO,
    fimalgoritmo: tiposDeSimbolos.FIM_ALGORITMO,
    fimenquanto: tiposDeSimbolos.FIM_ENQUANTO,
    fimescolha: tiposDeSimbolos.FIM_ESCOLHA,
    fimfuncao: tiposDeSimbolos.FIM_FUNCAO,
    fimpara: tiposDeSimbolos.FIM_PARA,
    funcao: tiposDeSimbolos.FUNCAO,
    inicio: tiposDeSimbolos.INICIO,
    inteiro: tiposDeSimbolos.INTEIRO,
    leia: tiposDeSimbolos.LEIA,
    logico: tiposDeSimbolos.LOGICO,
    outrocaso: tiposDeSimbolos.OUTRO_CASO,
    para: tiposDeSimbolos.PARA,
    real: tiposDeSimbolos.REAL,
    repita: tiposDeSimbolos.REPITA,
    var: tiposDeSimbolos.VAR,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
    vetor: tiposDeSimbolos.VETOR
};
