export * from './egua-classico';
export * from './mapler/interpretador-mapler';
export * from './mapler/interpretador-mapler-com-depuracao';
export * from './portugol-ipt/interpretador-portugol-ipt';
export * from './portugol-studio/interpretador-portugol-studio';
export * from './portugol-studio/interpretador-portugol-studio-com-depuracao';
export * from './potigol/interpretador-potigol';
export * from './visualg/interpretador-visualg';
export * from './visualg/interpretador-visualg-com-depuracao';
export * from './birl/interpretador-birl'
