export default {
    DICIONARIO: 'dicionario',
    DICIONÁRIO: 'dicionário',
    INTEIRO: 'inteiro',
    LOGICO: 'logico',
    LÓGICO: 'lógico',
    MODULO: 'modulo',
    MÓDULO: 'módulo',
    NUMERO: 'numero',
    NÚMERO: 'número',
    NULO: 'nulo',
    OBJETO: 'objeto',
    QUALQUER: 'qualquer',
    REAL: 'real',
    TEXTO: 'texto',
    TUPLA: 'tupla',
    VAZIO: 'vazio',
    VETOR: 'vetor',
    VETOR_NUMERO: 'numero[]',
    VETOR_NÚMERO: 'número[]',
    VETOR_TEXTO: 'texto[]',
};
