export default {
    BOOLEANO: 'boolean',
    DATA: 'Date',
    FUNCAO: 'function',
    INDEFINIDO: undefined,
    MAPA: 'Map',
    NULO: null,
    NUMERO: 'number',
    OBJETO: 'object',
    PROMESSA: 'Promise',
    QUALQUER: 'any',
    REGEX: 'RegExp',
    SIMBOLO: 'symbol',
    TEXTO: 'string',
};
