export default {
    DICIONARIO: 'dicionario',
    DICIONÁRIO: 'dicionário',
    INTEIRO: 'inteiro',
    LOGICO: 'logico',
    LÓGICO: 'lógico',
    MODULO: 'modulo',
    MÓDULO: 'módulo',
    NULO: 'nulo',
    OBJETO: 'objeto',
    QUALQUER: 'qualquer',
    REAL: 'real',
    TEXTO: 'texto',
    TUPLA: 'tupla',
    VAZIO: 'vazio',
    VETOR: 'vetor',
    VETOR_INTEIRO: 'inteiro[]',
    VETOR_LOGICO: 'logico[]',
    VETOR_LÓGICO: 'lógico[]',
    VETOR_QUALQUER: 'qualquer[]',
    VETOR_TEXTO: 'texto[]',
};
