export * from './chamavel';
export * from './classe-padrao';
export * from './delegua-classe';
export * from './funcao-padrao';
export * from './funcao';
export * from './metodo-primitiva';
export * from './modulo';
export * from './objeto-delegua-classe';
export * from './objeto-padrao';
