export default {
    // Comandos da linguagem do bambam
    HORA_DO_SHOW: 'HORA DO SHOW',
    BIRL: 'BIRL',
    CE_QUER_VER_ESSA_PORRA: 'CE QUER VER ESSA PORRA?',
    QUE_QUE_CE_QUER_MONSTRAO: 'QUE QUE CE QUER MONSTRAO?',
    ELE_QUE_A_GENTE_QUER: 'ELE QUE A GENTE QUER?',
    NAO_VAI_DAR_NAO: 'NAO VAI DAR NAO',
    QUE_NAO_VAI_DAR_O_QUE: 'QUE NAO VAI DAR O QUE?',
    NEGATIVA_BAMBAM: 'NEGATIVA BAMBAM',
    MAIS_QUERO_MAIS: 'MAIS QUERO MAIS',
    VAMO_MONSTRO: 'VAMO MONSTRO;',
    SAI_FILHO_DA_PUTA: 'SAI FILHO DA PUTA;',
    OH_O_HOME_AI_PO: 'OH O HOME AI PO',
    AJUDA_O_MALUCO_TA_DOENTE: 'AJUDA O MALUCO TA DOENTE',

    // simbolos
    PARENTESE_DIREITO: 'PARENTESE_DIREITO',
    PARENTESE_ESQUERDO: 'PARENTESE_ESQUERDO',
    IGUAL: 'IGUAL',
    IGUAL_IGUAL: 'IGUAL_IGUAL',
    PONTO_E_VIRGULA: 'PONTO_E_VIRGULA',

    // Types
    FR: 'TEXTO',
    M2: 'INTEIRO',
    M1: 'INTEIRO_CURTO',
    M3: 'INTEIRO_LONGO',
    T: 'PONTO_FLUTUANTE',
    TD: 'PONTO_FLUTUANTE_MAIS_PRECISO',
    BF: 'INTEIRO_NÃO_ASSINADO',
};
