export default {
    HORA_DO_SHOW: 'HORA_DO_SHOW',
    BIRL: 'BIRL',
    CE_QUER_VER_ESSA_PORRA: 'CE_QUER_VER_ESSA_PORRA',
    QUE_QUE_CE_QUER_MONSTRAO: 'QUE_QUE_CE_QUER_MONSTRAO',
    ELE_QUE_A_GENTE_QUER: 'ELE_QUE_A_GENTE_QUER',
    NAO_VAI_DAR_NAO: 'NAO_VAI_DAR_NAO',
    QUE_NAO_VAI_DAR_O_QUE: 'QUE_NAO_VAI_DAR_O_QUE',
    NEGATIVA_BAMBAM: 'NEGATIVA_BAMBAM',
    MAIS_QUERO_MAIS: 'MAIS_QUERO_MAIS',
    VAMO_MONSTRO: 'VAMO_MONSTRO',
    SAI_FILHO_DA_PUTA: 'SAI_FILHO_DA_PUTA',
    OH_O_HOME_AI_PO: 'OH_O_HOME_AI_PO',
    AJUDA_O_MALUCO_TA_DOENTE: 'AJUDA_O_MALUCO_TA_DOENTE',
    // simbolos
    PARENTESE_DIREITO: 'PARENTESE_DIREITO',
    PARENTESE_ESQUERDO: 'PARENTESE_ESQUERDO',
};
