export default {
    // Palavras reservadas
    A: 'A',
    AI: 'AI',
    AJUDA: 'AJUDA',
    BAMBAM: 'BAMBAM',
    BIRL: 'BIRL',
    BORA: 'BORA',
    CE: 'CE',
    CUMPADE: 'CUMPADE',
    DA: 'DA',
    DAR: 'DAR',
    DO: 'DO',
    DOENTE: 'DOENTE',
    ELE: 'ELE',
    ESSA: 'ESSA',
    FRANGAO: 'FRANGAO',
    FRANGÃO: 'FRANGÃO',
    FRANGO: 'FRANGO',
    FILHO: 'FILHO',
    GENTE: 'GENTE',
    HOME: 'HOME',
    HORA: 'HORA',
    MAIS: 'MAIS',
    MALUCO: 'MALUCO',
    MONSTRAO: 'MONSTRAO',
    MONSTRO: 'MONSTRO',
    TRAPEZIO: 'TRAPEZIO',
    NAO: 'NAO',
    NEGATIVA: 'NEGATIVA',
    NEGATIVO: 'NEGATIVO',
    O: 'O',
    OH: 'OH',
    PO: 'PO',
    PORRA: 'PORRA',
    POSITIVO: 'POSITIVO',
    PUTA: 'PUTA',
    QUE: 'QUE',
    QUER: 'QUER',
    QUERO: 'QUERO',
    SAI: 'SAI',
    SHOW: 'SHOW',
    TA: 'TA',
    VAI: 'VAI',
    VAMO: 'VAMO',
    VER: 'VER',

    // Símbolos de propósito geral
    IGUAL: 'IGUAL',
    PARENTESE_DIREITO: 'PARENTESE_DIREITO',
    PARENTESE_ESQUERDO: 'PARENTESE_ESQUERDO',
    PONTO_E_VIRGULA: 'PONTO_E_VIRGULA',
    QUEBRA_LINHA: 'QUEBRA_LINHA',
    INTERROGACAO: 'INTERROGACAO',
    VIRGULA: 'VIRGULA',

    // Operações matemáticas
    ADICAO: 'ADICAO',
    SUBTRACAO: 'SUBTRACAO',
    MULTIPLICACAO: 'MULTIPLICACAO',
    DIVISAO: 'DIVISAO',
    MODULO: 'MODULO',

    // Comparadores
    IGUAL_IGUAL: 'IGUAL_IGUAL',
    MAIOR: 'MAIOR',
    MAIOR_IGUAL: 'MAIOR_IGUAL',
    MENOR: 'MENOR',
    MENOR_IGUAL: 'MENOR_IGUAL',

    // Tipos de dados
    TEXTO: 'TEXTO',
    NUMERO: 'NUMERO',
    IDENTIFICADOR: 'IDENTIFICADOR',

    // SINTAXE BIRL
    PONTEIRO: 'PONTEIRO',
};
