export default {
    ADICAO: "ADICAO",
    DIFERENTE: "DIFERENTE",
    DIVISAO: "DIVISAO",
    E: "E",
    IDENTIFICADOR: "IDENTIFICADOR",
    IGUAL: "IGUAL",
    MAIOR: "MAIOR",
    MAIOR_IGUAL: "MAIOR_IGUAL",
    MENOR: "MENOR",
    MENOR_IGUAL: "MENOR_IGUAL",
    MODULO: "MODULO",
    MULTIPLICACAO: "MULTIPLICACAO",
    NEGACAO: "NEGACAO",
    OU: "OU",
    SUBTRACAO: "SUBTRACAO"
}