export default {
    OI: 'OI', // E,
    PE: 'PE', // Em
    HAI: 'HAI', // Escreva

    CHAVE_ESQUERDA: 'CHAVE_ESQUERDA',
    CHAVE_DIREITA: 'CHAVE_DIREITA',
    IDENTIFICADOR: 'IDENTIFICADOR',
    NUMERO: 'NUMERO',
    PARENTESE_DIREITO: 'PARENTESE_DIREITO',
    PARENTESE_ESQUERDO: 'PARENTESE_ESQUERDO',
    TEXTO: 'TEXTO',
    VIRGULA: 'VIRGULA'
}