export default {
    ALGORITMO: "ALGORITMO",
    CARACTERE: "CARACTERE",
    FIMALGORITMO: "FIMALGORITMO",
    IDENTIFICADOR: "IDENTIFICADOR",
    INICIO: "INICIO",
    NUMERO: "NUMERO",
    QUEBRA_LINHA: "QUEBRA_LINHA",
    VAR: "VAR"
}