export default {
    ALGORITMO: "ALGORITMO",
    ATE: "ATE",
    CARACTERE: "CARACTERE",
    DE: "DE",
    ESCREVA: "ESCREVA",
    FACA: "FACA",
    FIMALGORITMO: "FIMALGORITMO",
    FIMPARA: "FIMPARA",
    IDENTIFICADOR: "IDENTIFICADOR",
    INICIO: "INICIO",
    NUMERO: "NUMERO",
    PARENTESE_DIREITO: "PARENTESE_DIREITO",
    PARENTESE_ESQUERDO: "PARENTESE_ESQUERDO",
    QUEBRA_LINHA: "QUEBRA_LINHA",
    VAR: "VAR"
}