// TODO: Marcado para depreciação.
export type TipoDadosElementar =
    | 'dicionário'
    | 'função'
    | 'inteiro'
    | 'inteiro[]'
    | 'longo'
    | 'longo[]'
    | 'lógico'
    | 'lógico[]'
    | 'módulo'
    | 'nulo'
    | 'número'
    | 'número[]'
    | 'qualquer'
    | 'qualquer[]'
    | 'real'
    | 'real[]'
    | 'símbolo'
    | 'texto'
    | 'texto[]'
    | 'caracter'
    | 'caracter[]'
    | undefined;
